// Túdó — sample data (Icelandic)

const TUDO_SUBJECTS = [
  { id: 'staerd', name: 'Stærðfræði', emoji: '∑', color: '#1B2A6B' },
  { id: 'enska', name: 'Enska', emoji: 'A', color: '#3D4B9E' },
  { id: 'edli', name: 'Eðlisfræði', emoji: '⚛', color: '#5A6BC4' },
  { id: 'jardf', name: 'Jarðfræði', emoji: '◯', color: '#8590D8' },
];

const TUDO_TEACHERS = [
  {
    id: 't1',
    name: 'Anna Sigurðardóttir',
    initials: 'AS',
    avatarBg: '#1B2A6B',
    avatarFg: '#B8C0EE',
    subjects: ['Stærðfræði', 'Eðlisfræði'],
    subjectIds: ['staerd', 'edli'],
    degree: 'MSc',
    rating: 4.9,
    reviews: 47,
    price: 6500,
    location: 'Reykjavík',
    online: true,
    inPerson: true,
    bio: 'Ég er meistaranemi í eðlisfræði við HÍ og hef kennt menntaskólanemum stærðfræði og eðlisfræði í þrjú ár. Mér finnst best að útskýra hluti með myndrænum dæmum og raunverulegum aðstæðum.',
    levels: ['Grunnskóli', 'Menntaskóli', 'Háskóli (1. ár)'],
    experience: '3 ár',
    languages: ['Íslenska', 'Enska'],
  },
  {
    id: 't2',
    name: 'Jón Þór Bjarnason',
    initials: 'JB',
    avatarBg: '#3D4B9E',
    avatarFg: '#EEF0FF',
    subjects: ['Enska', 'Íslenska'],
    subjectIds: ['enska'],
    degree: 'BA',
    rating: 4.8,
    reviews: 32,
    price: 5500,
    location: 'Reykjavík',
    online: true,
    inPerson: false,
    bio: 'Ég er á þriðja ári í enskum bókmenntum við HÍ. Hef búið í London og hjálpa nemendum með ritgerðir, framburð og lesskilning.',
    levels: ['Grunnskóli', 'Menntaskóli'],
    experience: '2 ár',
    languages: ['Íslenska', 'Enska'],
  },
  {
    id: 't3',
    name: 'Sara Kristinsdóttir',
    initials: 'SK',
    avatarBg: '#5A6BC4',
    avatarFg: '#FFFFFF',
    subjects: ['Jarðfræði', 'Eðlisfræði'],
    subjectIds: ['jardf', 'edli'],
    degree: 'PhD',
    rating: 5.0,
    reviews: 18,
    price: 8000,
    location: 'Akureyri',
    online: true,
    inPerson: true,
    bio: 'Doktor í jarðvísindum með áralanga reynslu af kennslu í menntaskóla og háskóla. Sérgrein: eldfjöll og jarðskjálftar.',
    levels: ['Menntaskóli', 'Háskóli'],
    experience: '8 ár',
    languages: ['Íslenska', 'Enska', 'Danska'],
  },
  {
    id: 't4',
    name: 'Kári Magnússon',
    initials: 'KM',
    avatarBg: '#8590D8',
    avatarFg: '#1B2A6B',
    subjects: ['Stærðfræði'],
    subjectIds: ['staerd'],
    degree: 'BSc',
    rating: 4.7,
    reviews: 24,
    price: 5000,
    location: 'Hafnarfjörður',
    online: false,
    inPerson: true,
    bio: 'Á öðru ári í verkfræði við HR. Hef kennt yngri systkinum og vinum árum saman og elska að einfalda erfiða útreikninga.',
    levels: ['Grunnskóli', 'Menntaskóli'],
    experience: '1 ár',
    languages: ['Íslenska'],
  },
  {
    id: 't5',
    name: 'Helga Björnsdóttir',
    initials: 'HB',
    avatarBg: '#1B2A6B',
    avatarFg: '#B8C0EE',
    subjects: ['Enska'],
    subjectIds: ['enska'],
    degree: 'MA',
    rating: 4.9,
    reviews: 56,
    price: 7000,
    location: 'Reykjavík',
    online: true,
    inPerson: true,
    bio: 'Enskukennari í menntaskóla með MA í enskukennslu. Sérhæfi mig í undirbúningi fyrir IELTS og TOEFL próf.',
    levels: ['Menntaskóli', 'Háskóli', 'Fullorðnir'],
    experience: '6 ár',
    languages: ['Íslenska', 'Enska'],
  },
  {
    id: 't6',
    name: 'Daníel Ingvarsson',
    initials: 'DI',
    avatarBg: '#3D4B9E',
    avatarFg: '#EEF0FF',
    subjects: ['Jarðfræði'],
    subjectIds: ['jardf'],
    degree: 'BSc',
    rating: 4.6,
    reviews: 12,
    price: 4500,
    location: 'Reykjavík',
    online: true,
    inPerson: false,
    bio: 'Á lokaári í jarðfræði við HÍ. Hjálpa nemendum að skilja landrek, jarðlög og íslenska jarðsögu.',
    levels: ['Menntaskóli'],
    experience: '1 ár',
    languages: ['Íslenska', 'Enska'],
  },
];

// Sample chats — Icelandic
const TUDO_CHATS = [
  {
    id: 'c1',
    teacherId: 't1',
    lastMessage: 'Sjáumst á morgun kl. 16!',
    lastTime: '10:42',
    unread: 0,
    messages: [
      { from: 'them', text: 'Hæ! Takk fyrir bókunina 🙌', time: '09:12' },
      { from: 'me', text: 'Hæ Anna! Hlakka til. Ég er svolítið stressuð fyrir prófinu.', time: '09:14' },
      { from: 'them', text: 'Engar áhyggjur, við förum yfir öll dæmin saman. Geturðu sent mér efnislistann?', time: '09:15' },
      { from: 'me', text: 'Já klárlega, sendi á þig núna 📚', time: '09:16' },
      { from: 'them', text: 'Frábært! Sjáumst á morgun kl. 16!', time: '10:42' },
    ],
  },
  {
    id: 'c2',
    teacherId: 't5',
    lastMessage: 'Ég sendi þér nokkur dæmi til að skoða',
    lastTime: 'Í gær',
    unread: 2,
    messages: [
      { from: 'me', text: 'Hæ Helga, getum við hist í næstu viku?', time: 'Mán' },
      { from: 'them', text: 'Já endilega! Hvenær hentar þér?', time: 'Mán' },
      { from: 'them', text: 'Ég sendi þér nokkur dæmi til að skoða', time: 'Í gær' },
    ],
  },
  {
    id: 'c3',
    teacherId: 't3',
    lastMessage: 'Takk fyrir tímann í dag!',
    lastTime: 'Mán',
    unread: 0,
    messages: [
      { from: 'them', text: 'Takk fyrir tímann í dag!', time: 'Mán' },
    ],
  },
];

// Bookings
const TUDO_BOOKINGS = {
  upcoming: [
    { id: 'b1', teacherId: 't1', subject: 'Stærðfræði', date: 'Á morgun', time: '16:00 – 17:00', mode: 'Á netinu', price: 6500 },
    { id: 'b2', teacherId: 't5', subject: 'Enska', date: 'Fim 7. maí', time: '14:30 – 15:30', mode: 'Hjá kennara', price: 7000 },
  ],
  past: [
    { id: 'b3', teacherId: 't3', subject: 'Jarðfræði', date: '2. maí', time: '17:00 – 18:00', mode: 'Á netinu', price: 8000, rated: 5 },
    { id: 'b4', teacherId: 't1', subject: 'Eðlisfræði', date: '28. apríl', time: '16:00 – 17:00', mode: 'Á netinu', price: 6500, rated: 5 },
    { id: 'b5', teacherId: 't4', subject: 'Stærðfræði', date: '24. apríl', time: '15:00 – 16:00', mode: 'Hjá nemanda', price: 5000, rated: 4 },
  ],
};

window.TUDO_SUBJECTS = TUDO_SUBJECTS;
window.TUDO_TEACHERS = TUDO_TEACHERS;
window.TUDO_CHATS = TUDO_CHATS;
window.TUDO_BOOKINGS = TUDO_BOOKINGS;
